

-- add new user
INSERT INTO USER(NAME, EMAIL, PHONE, MINER_COUNT) VALUES('Gokhan', 'gkhncetin@gmail.com', '+905336292790', 1);
-- add wallet to user
INSERT INTO WALLET(ADDRESS, USER_ID, TOTAL_EARNED) VALUES('3JXK2RJd65dfHEcX23F34hCRnYJgQy6ktk', 4, 0);
