-- add pool column to table wallet
CREATE TABLE WALLET2 ("ADDRESS"	TEXT, "POOL" TEXT DEFAULT "AHASH", "USER_ID"	INTEGER NOT NULL, "TOTAL_EARNED" REAL NOT NULL, "LAST_UPDATE" TEXT DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY("ADDRESS","POOL"));
INSERT INTO WALLET2 (ADDRESS, USER_ID, TOTAL_EARNED, LAST_UPDATE) SELECT ADDRESS, USER_ID, TOTAL_EARNED, LAST_UPDATE FROM WALLET;
DROP TABLE WALLET;
ALTER TABLE "WALLET2" RENAME TO "WALLET";

